version: '3.7'

services:
  ogiri_mysql:
    container_name: ogiri_db
    image: library/mysql:5.7
    volumes:
      - ./db/data:/var/lib/mysql
      - ./schema:/docker-entrypoint-initdb.d
    env_file: .env
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ogiri
