// Package database contains the types for schema 'ogiri'.
package database

// Code generated by xo. DO NOT EDIT.

import (
	"errors"
)

// User represents a row from 'ogiri.user'.
type User struct {
	ID       int    `json:"id"`       // id
	Name     string `json:"name"`     // name
	Password string `json:"password"` // password

	// xo fields
	_exists, _deleted bool
}

// Exists determines if the User exists in the database.
func (u *User) Exists() bool {
	return u._exists
}

// Deleted provides information if the User has been deleted from the database.
func (u *User) Deleted() bool {
	return u._deleted
}

// Insert inserts the User to the database.
func (u *User) Insert(db XODB) error {
	var err error

	// if already exist, bail
	if u._exists {
		return errors.New("insert failed: already exists")
	}

	// sql insert query, primary key provided by autoincrement
	const sqlstr = `INSERT INTO ogiri.user (` +
		`name, password` +
		`) VALUES (` +
		`?, ?` +
		`)`

	// run query
	XOLog(sqlstr, u.Name, u.Password)
	res, err := db.Exec(sqlstr, u.Name, u.Password)
	if err != nil {
		return err
	}

	// retrieve id
	id, err := res.LastInsertId()
	if err != nil {
		return err
	}

	// set primary key and existence
	u.ID = int(id)
	u._exists = true

	return nil
}

// Update updates the User in the database.
func (u *User) Update(db XODB) error {
	var err error

	// if doesn't exist, bail
	if !u._exists {
		return errors.New("update failed: does not exist")
	}

	// if deleted, bail
	if u._deleted {
		return errors.New("update failed: marked for deletion")
	}

	// sql query
	const sqlstr = `UPDATE ogiri.user SET ` +
		`name = ?, password = ?` +
		` WHERE id = ?`

	// run query
	XOLog(sqlstr, u.Name, u.Password, u.ID)
	_, err = db.Exec(sqlstr, u.Name, u.Password, u.ID)
	return err
}

// Save saves the User to the database.
func (u *User) Save(db XODB) error {
	if u.Exists() {
		return u.Update(db)
	}

	return u.Insert(db)
}

// Delete deletes the User from the database.
func (u *User) Delete(db XODB) error {
	var err error

	// if doesn't exist, bail
	if !u._exists {
		return nil
	}

	// if deleted, bail
	if u._deleted {
		return nil
	}

	// sql query
	const sqlstr = `DELETE FROM ogiri.user WHERE id = ?`

	// run query
	XOLog(sqlstr, u.ID)
	_, err = db.Exec(sqlstr, u.ID)
	if err != nil {
		return err
	}

	// set deleted
	u._deleted = true

	return nil
}

// UserByName retrieves a row from 'ogiri.user' as a User.
//
// Generated from index 'name'.
func UserByName(db XODB, name string) (*User, error) {
	var err error

	// sql query
	const sqlstr = `SELECT ` +
		`id, name, password ` +
		`FROM ogiri.user ` +
		`WHERE name = ?`

	// run query
	XOLog(sqlstr, name)
	u := User{
		_exists: true,
	}

	err = db.QueryRow(sqlstr, name).Scan(&u.ID, &u.Name, &u.Password)
	if err != nil {
		return nil, err
	}

	return &u, nil
}

// UserByID retrieves a row from 'ogiri.user' as a User.
//
// Generated from index 'user_id_pkey'.
func UserByID(db XODB, id int) (*User, error) {
	var err error

	// sql query
	const sqlstr = `SELECT ` +
		`id, name, password ` +
		`FROM ogiri.user ` +
		`WHERE id = ?`

	// run query
	XOLog(sqlstr, id)
	u := User{
		_exists: true,
	}

	err = db.QueryRow(sqlstr, id).Scan(&u.ID, &u.Name, &u.Password)
	if err != nil {
		return nil, err
	}

	return &u, nil
}
