// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

package ogiri

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{0}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

// ユーザーに大喜利のネタを通知する
type Ogiri struct {
	OgiriId              string   `protobuf:"bytes,1,opt,name=ogiri_id,json=ogiriId,proto3" json:"ogiri_id,omitempty"`
	OdaiId               string   `protobuf:"bytes,2,opt,name=odai_id,json=odaiId,proto3" json:"odai_id,omitempty"`
	AnswerDuration       int64    `protobuf:"varint,3,opt,name=answer_duration,json=answerDuration,proto3" json:"answer_duration,omitempty"`
	VoteDuration         int64    `protobuf:"varint,4,opt,name=vote_duration,json=voteDuration,proto3" json:"vote_duration,omitempty"`
	QuestionDuration     int64    `protobuf:"varint,5,opt,name=question_duration,json=questionDuration,proto3" json:"question_duration,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Ogiri) Reset()         { *m = Ogiri{} }
func (m *Ogiri) String() string { return proto.CompactTextString(m) }
func (*Ogiri) ProtoMessage()    {}
func (*Ogiri) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{1}
}

func (m *Ogiri) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ogiri.Unmarshal(m, b)
}
func (m *Ogiri) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ogiri.Marshal(b, m, deterministic)
}
func (m *Ogiri) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ogiri.Merge(m, src)
}
func (m *Ogiri) XXX_Size() int {
	return xxx_messageInfo_Ogiri.Size(m)
}
func (m *Ogiri) XXX_DiscardUnknown() {
	xxx_messageInfo_Ogiri.DiscardUnknown(m)
}

var xxx_messageInfo_Ogiri proto.InternalMessageInfo

func (m *Ogiri) GetOgiriId() string {
	if m != nil {
		return m.OgiriId
	}
	return ""
}

func (m *Ogiri) GetOdaiId() string {
	if m != nil {
		return m.OdaiId
	}
	return ""
}

func (m *Ogiri) GetAnswerDuration() int64 {
	if m != nil {
		return m.AnswerDuration
	}
	return 0
}

func (m *Ogiri) GetVoteDuration() int64 {
	if m != nil {
		return m.VoteDuration
	}
	return 0
}

func (m *Ogiri) GetQuestionDuration() int64 {
	if m != nil {
		return m.QuestionDuration
	}
	return 0
}

// 自分のボケを送信する
type BokeRequest struct {
	Answerer             int64    `protobuf:"varint,1,opt,name=answerer,proto3" json:"answerer,omitempty"`
	Boke                 string   `protobuf:"bytes,2,opt,name=boke,proto3" json:"boke,omitempty"`
	OgiriId              string   `protobuf:"bytes,3,opt,name=ogiri_id,json=ogiriId,proto3" json:"ogiri_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BokeRequest) Reset()         { *m = BokeRequest{} }
func (m *BokeRequest) String() string { return proto.CompactTextString(m) }
func (*BokeRequest) ProtoMessage()    {}
func (*BokeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{2}
}

func (m *BokeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BokeRequest.Unmarshal(m, b)
}
func (m *BokeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BokeRequest.Marshal(b, m, deterministic)
}
func (m *BokeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BokeRequest.Merge(m, src)
}
func (m *BokeRequest) XXX_Size() int {
	return xxx_messageInfo_BokeRequest.Size(m)
}
func (m *BokeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BokeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BokeRequest proto.InternalMessageInfo

func (m *BokeRequest) GetAnswerer() int64 {
	if m != nil {
		return m.Answerer
	}
	return 0
}

func (m *BokeRequest) GetBoke() string {
	if m != nil {
		return m.Boke
	}
	return ""
}

func (m *BokeRequest) GetOgiriId() string {
	if m != nil {
		return m.OgiriId
	}
	return ""
}

// ボケに投票する
type VoteRequest struct {
	OgiriId              string   `protobuf:"bytes,1,opt,name=ogiri_id,json=ogiriId,proto3" json:"ogiri_id,omitempty"`
	BokeId               int64    `protobuf:"varint,2,opt,name=boke_id,json=bokeId,proto3" json:"boke_id,omitempty"`
	AnswererId           int64    `protobuf:"varint,3,opt,name=answerer_id,json=answererId,proto3" json:"answerer_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VoteRequest) Reset()         { *m = VoteRequest{} }
func (m *VoteRequest) String() string { return proto.CompactTextString(m) }
func (*VoteRequest) ProtoMessage()    {}
func (*VoteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{3}
}

func (m *VoteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VoteRequest.Unmarshal(m, b)
}
func (m *VoteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VoteRequest.Marshal(b, m, deterministic)
}
func (m *VoteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VoteRequest.Merge(m, src)
}
func (m *VoteRequest) XXX_Size() int {
	return xxx_messageInfo_VoteRequest.Size(m)
}
func (m *VoteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_VoteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_VoteRequest proto.InternalMessageInfo

func (m *VoteRequest) GetOgiriId() string {
	if m != nil {
		return m.OgiriId
	}
	return ""
}

func (m *VoteRequest) GetBokeId() int64 {
	if m != nil {
		return m.BokeId
	}
	return 0
}

func (m *VoteRequest) GetAnswererId() int64 {
	if m != nil {
		return m.AnswererId
	}
	return 0
}

// 次のお題を送信する
type OdaiRequest struct {
	QuestionerId         int64    `protobuf:"varint,1,opt,name=questioner_id,json=questionerId,proto3" json:"questioner_id,omitempty"`
	Odai                 string   `protobuf:"bytes,2,opt,name=odai,proto3" json:"odai,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OdaiRequest) Reset()         { *m = OdaiRequest{} }
func (m *OdaiRequest) String() string { return proto.CompactTextString(m) }
func (*OdaiRequest) ProtoMessage()    {}
func (*OdaiRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{4}
}

func (m *OdaiRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OdaiRequest.Unmarshal(m, b)
}
func (m *OdaiRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OdaiRequest.Marshal(b, m, deterministic)
}
func (m *OdaiRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OdaiRequest.Merge(m, src)
}
func (m *OdaiRequest) XXX_Size() int {
	return xxx_messageInfo_OdaiRequest.Size(m)
}
func (m *OdaiRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_OdaiRequest.DiscardUnknown(m)
}

var xxx_messageInfo_OdaiRequest proto.InternalMessageInfo

func (m *OdaiRequest) GetQuestionerId() int64 {
	if m != nil {
		return m.QuestionerId
	}
	return 0
}

func (m *OdaiRequest) GetOdai() string {
	if m != nil {
		return m.Odai
	}
	return ""
}

func init() {
	proto.RegisterType((*Empty)(nil), "ogiri.Empty")
	proto.RegisterType((*Ogiri)(nil), "ogiri.Ogiri")
	proto.RegisterType((*BokeRequest)(nil), "ogiri.BokeRequest")
	proto.RegisterType((*VoteRequest)(nil), "ogiri.VoteRequest")
	proto.RegisterType((*OdaiRequest)(nil), "ogiri.OdaiRequest")
}

func init() { proto.RegisterFile("api.proto", fileDescriptor_00212fb1f9d3bf1c) }

var fileDescriptor_00212fb1f9d3bf1c = []byte{
	// 275 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x51, 0xbd, 0x4e, 0xc3, 0x30,
	0x10, 0x56, 0x70, 0x93, 0xb4, 0x97, 0x96, 0x1f, 0x2f, 0x14, 0x16, 0x2a, 0x77, 0xa0, 0x12, 0x12,
	0x0b, 0x6f, 0x80, 0x00, 0xc9, 0x53, 0x25, 0x0f, 0x88, 0xad, 0x72, 0x64, 0x0b, 0x59, 0x15, 0x75,
	0x70, 0x5d, 0x10, 0x2f, 0xc6, 0xf3, 0x21, 0x5f, 0x7a, 0x89, 0xb2, 0xb0, 0xdd, 0xf7, 0x13, 0x7f,
	0xf7, 0x5d, 0x60, 0xa2, 0x1b, 0x77, 0xdf, 0x04, 0x1f, 0x3d, 0xcf, 0xfd, 0xbb, 0x0b, 0x4e, 0x94,
	0x90, 0x3f, 0x7f, 0x34, 0xf1, 0x47, 0xfc, 0x66, 0x90, 0xaf, 0x13, 0xc5, 0xaf, 0x60, 0x8c, 0xda,
	0xc6, 0x99, 0x79, 0xb6, 0xc8, 0x56, 0x13, 0x55, 0x22, 0x96, 0x86, 0x5f, 0x42, 0xe9, 0x8d, 0x46,
	0xe5, 0x04, 0x95, 0x22, 0x41, 0x69, 0xf8, 0x2d, 0x9c, 0xe9, 0xdd, 0xfe, 0xdb, 0x86, 0x8d, 0x39,
	0x04, 0x1d, 0x9d, 0xdf, 0xcd, 0xd9, 0x22, 0x5b, 0x31, 0x75, 0xda, 0xd2, 0x4f, 0x47, 0x96, 0x2f,
	0x61, 0xf6, 0xe5, 0xa3, 0xed, 0x6d, 0x23, 0xb4, 0x4d, 0x13, 0xd9, 0x99, 0xee, 0xe0, 0xe2, 0xf3,
	0x60, 0xf7, 0x69, 0xee, 0x8d, 0x39, 0x1a, 0xcf, 0x49, 0x20, 0xb3, 0x78, 0x83, 0xea, 0xd1, 0x6f,
	0xad, 0xb2, 0xa8, 0xf0, 0x6b, 0x18, 0xb7, 0x91, 0x36, 0xe0, 0xf6, 0x4c, 0x75, 0x98, 0x73, 0x18,
	0xd5, 0x7e, 0x6b, 0x8f, 0xbb, 0xe3, 0x3c, 0x68, 0xcb, 0x06, 0x6d, 0x45, 0x0d, 0xd5, 0xab, 0x8f,
	0xdd, 0xcb, 0xff, 0xdf, 0x25, 0x3d, 0x46, 0x77, 0x61, 0xaa, 0x48, 0x50, 0x1a, 0x7e, 0x03, 0x15,
	0xa5, 0x53, 0x00, 0x53, 0x40, 0x94, 0x34, 0xe2, 0x05, 0xaa, 0xb5, 0xd1, 0x8e, 0x32, 0x96, 0x30,
	0xa3, 0x82, 0xed, 0x17, 0x6d, 0x85, 0x69, 0x4f, 0x4a, 0x93, 0x6a, 0xa4, 0xb3, 0x53, 0x8d, 0x34,
	0xd7, 0x05, 0xfe, 0xd5, 0x87, 0xbf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xcb, 0x8c, 0x46, 0x8a, 0xe2,
	0x01, 0x00, 0x00,
}
